events {}

http {
    server {
        listen 80;

        location /auth/ {
            proxy_pass http://auth:3000/;
        }

        location /products/ {
            proxy_pass http://products:3000/;
        }

        location /orders/ {
            proxy_pass http://orders:3000/;
        }
    }
}
